print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/julianmitton/Documents/Unity Projects/1610Spring2022Backup/My project/Assets/Maya/assets/Assets/PB Idle.ma"`)
{		
	file -o "/Users/julianmitton/Documents/Unity Projects/1610Spring2022Backup/My project/Assets/Maya/assets/Assets/PB Idle.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/julianmitton/Documents/Unity Projects/1610Spring2022Backup/My project/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/julianmitton/Documents/Unity Projects/1610Spring2022Backup/My project/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/julianmitton/Documents/Unity Projects/1610Spring2022Backup/My project/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
